- name: Test connectivity
  # apply this play on all host in the inventory
  hosts: all
  tasks:
    - name: Ping the host
      ping:
    - name: Echo a message
      debug:
        msg: "user running this task {{ ansible_user }}, IP address is {{ ansible_host }}"
    - name: Time and date on the server
      shell:
        cmd: echo "The current time/date is $(date)"

